import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

export default async (sock, msg, args, extra) => {
    const chat = msg.key.remoteJid;

    if (!args.length) {
        return await sock.sendMessage(chat, {
            text: '❌ Please provide text to convert to PDF.\n\nUsage: *.pdf* <your text here>'
        }, { quoted: msg });
    }

    await sock.sendMessage(chat, { react: { text: '📄', key: msg.key } });

    const text = args.join(' ');
    const outPath = path.join('/tmp', `nexa_${Date.now()}.pdf`);

    try {
        await new Promise((resolve, reject) => {
            const doc = new PDFDocument({ margin: 50 });
            const stream = fs.createWriteStream(outPath);

            doc.pipe(stream);

            doc.fontSize(20).fillColor('#0066cc').text('NEXA-BOT MD', { align: 'center' });
            doc.moveDown(0.5);
            doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#0066cc').stroke();
            doc.moveDown(1);

            doc.fontSize(12).fillColor('#000000').text(text, { align: 'left', lineGap: 4 });

            doc.moveDown(2);
            doc.fontSize(9).fillColor('#888888').text(`Generated by Nexa-Bot MD | ${new Date().toLocaleString()}`, { align: 'center' });

            doc.end();
            stream.on('finish', resolve);
            stream.on('error', reject);
        });

        await sock.sendMessage(chat, {
            document: fs.readFileSync(outPath),
            mimetype: 'application/pdf',
            fileName: 'nexa_output.pdf',
            caption: '📄 *Here is your PDF!*\n\n> Generated by Nexa-Bot MD'
        }, { quoted: msg });

        fs.unlinkSync(outPath);
    } catch (e) {
        console.error('PDF Error:', e);
        await sock.sendMessage(chat, { text: '❌ Failed to generate PDF.' }, { quoted: msg });
    }
};
